---
apiVersion: v1
kind: Service
metadata:
  name: testing5
  namespace: team1
  labels:
    app: testing5
    service: testing5
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: testing5